"""hozzáadtam a charity adatokat

Revision ID: 035399f12f63
Revises: 7e08743d49df
Create Date: 2019-10-26 16:13:00.791219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035399f12f63'
down_revision = '7e08743d49df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charity', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('charity', sa.Column('contact_email', sa.String(length=120), nullable=True))
    op.add_column('charity', sa.Column('contact_name', sa.String(length=100), nullable=True))
    op.add_column('charity', sa.Column('contact_phone_number', sa.String(length=20), nullable=True))
    op.add_column('charity', sa.Column('organisation_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_charity_contact_email'), 'charity', ['contact_email'], unique=True)
    op.create_unique_constraint(None, 'charity', ['organisation_name'])
    op.add_column('product', sa.Column('handling_category', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('product_category', sa.Integer(), nullable=True))
    op.drop_column('product', 'HandlingCategory')
    op.drop_column('product', 'ProductCategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('ProductCategory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('HandlingCategory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'product_category')
    op.drop_column('product', 'handling_category')
    op.drop_constraint(None, 'charity', type_='unique')
    op.drop_index(op.f('ix_charity_contact_email'), table_name='charity')
    op.drop_column('charity', 'organisation_name')
    op.drop_column('charity', 'contact_phone_number')
    op.drop_column('charity', 'contact_name')
    op.drop_column('charity', 'contact_email')
    op.drop_column('charity', 'address')
    # ### end Alembic commands ###
