"""cart

Revision ID: 051fa05d2037
Revises: 396b8533b500
Create Date: 2019-10-26 21:36:45.765990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051fa05d2037'
down_revision = '396b8533b500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'product_id')
    )
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'])
    op.add_column('user', sa.Column('cart_is_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cart_is_open')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'product_id')
    op.drop_table('order')
    # ### end Alembic commands ###
