"""empty message

Revision ID: 13096c30d498
Revises: a68c7d170cef
Create Date: 2019-10-26 15:26:33.113799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13096c30d498'
down_revision = 'a68c7d170cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('ProductCategory', sa.Integer(), nullable=True))
    op.drop_column('product', 'FoodCategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('FoodCategory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product', 'ProductCategory')
    # ### end Alembic commands ###
