"""StUpdate product models.

Revision ID: 396b8533b500
Revises: d27fd3eef249
Create Date: 2019-10-26 20:45:18.605733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396b8533b500'
down_revision = 'd27fd3eef249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('chain_product_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('product_category', sa.Integer(), nullable=False),
    sa.Column('handling_category', sa.Integer(), nullable=False),
    sa.Column('reuse_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.ForeignKeyConstraint(['handling_category'], ['handling_category.id'], ),
    sa.ForeignKeyConstraint(['product_category'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['reuse_category'], ['use_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('product', 'name')
    op.drop_column('product', 'handling_category')
    op.drop_column('product', 'product_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('handling_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_table('product_mapping')
    # ### end Alembic commands ###
