"""handling, username

Revision ID: 9f9b21e63892
Revises: 13096c30d498
Create Date: 2019-10-26 15:39:29.749030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9b21e63892'
down_revision = '13096c30d498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handling_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('HandlingCategory', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_name', table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_name', 'user', ['name'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('product', 'HandlingCategory')
    op.drop_table('handling_category')
    # ### end Alembic commands ###
