"""Store-user, store-chain relationships

Revision ID: bb7b826f042f
Revises: 035399f12f63
Create Date: 2019-10-26 17:22:08.329569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7b826f042f'
down_revision = '035399f12f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores_managed_by_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'store_id')
    )
    op.drop_table('connect_user_stores')
    op.add_column('stores', sa.Column('chain_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stores', 'chain', ['chain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'chain_id')
    op.create_table('connect_user_stores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='connect_user_stores_pkey')
    )
    op.drop_table('stores_managed_by_user')
    # ### end Alembic commands ###
