"""StCharity many-many fields. RequestType removed.

Revision ID: d27fd3eef249
Revises: bb7b826f042f
Create Date: 2019-10-26 18:20:05.648595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27fd3eef249'
down_revision = 'bb7b826f042f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity_handling_categories',
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('handling_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charity.id'], ),
    sa.ForeignKeyConstraint(['handling_id'], ['handling_category.id'], ),
    sa.PrimaryKeyConstraint('charity_id', 'handling_id')
    )
    op.create_table('charity_product_categories',
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charity.id'], ),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('charity_id', 'product_category_id')
    )
    op.create_table('charity_reuse_categories',
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('reuse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['charity.id'], ),
    sa.ForeignKeyConstraint(['reuse_id'], ['use_category.id'], ),
    sa.PrimaryKeyConstraint('charity_id', 'reuse_id')
    )
    op.drop_table('request_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='request_type_pkey')
    )
    op.drop_table('charity_reuse_categories')
    op.drop_table('charity_product_categories')
    op.drop_table('charity_handling_categories')
    # ### end Alembic commands ###
